# Generated by Django 3.0.1 on 2019-12-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdemoblog', '0006_auto_20191225_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
