# Generated by Django 3.0.1 on 2019-12-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdemoblog', '0010_auto_20191225_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
